### ISSUE TITLE
Gruppierung der Auswertung

### ISSUE THREAD

**Issue by Osslack** [Osslack/HANA_SSBM#24]
Für jeden der Subqueries getrennt -> q1.1,q1.2....

Und Gesamtllaufzeit.

**Comment by Pfeifenjoy** [comment]
![bildschirmfoto 2017-03-23 um 17 06 38](https://cloud.githubusercontent.com/assets/8148840/24257473/48d59a54-0feb-11e7-86d0-0e93119e3df9.png)

**Comment by Pfeifenjoy** [comment]
it would be nice two have two comparisons.
1. Table as described above
2. line Plot which shows the difference of all queries

**Comment by Pfeifenjoy** [comment]
@Osslack soll ich das noch im Dokument erwähnen
Habe jetzt Queries mit einander verglichen, wollte aber nicht einfach die rohen daten da reinklatschen.

**Comment by Pfeifenjoy** [comment]
sollte erledigt sein
https://github.com/Osslack/HANA_SSBM/commit/d96777f6576a9cc4f0eeae37b9311b3f36958541
