### ISSUE TITLE
Ausführung des Benchmarks

### ISSUE THREAD

**Issue by Pfeifenjoy** [Osslack/HANA_SSBM#33]
Erstelle ein Kapitel welches die Ausführung des Benchmarks beschreibt.

- Erstmal generell was ist unser Ansatz
    - benchmark als bash script ausführen auf unterschiedlichen PC's
    - benchmark daten in einem log speichern
    - benchmark analysieren durch automatisierten
    - Ergebnisse in Dokument vergleichen
- Wie verwendet man das Script
- Welche Harware configs untersuchen wir?

**Comment by jrjg** [comment]
ziele: 
- mehrfache wdh für ausreisser checken
- unterschiedliche schemata: row column index
- hardware vergleichen
- anderen zur verfügung stellen durch skripte

vorgehensweise: grafik, uml diagram, flussdiagram: schema anlegen:
- daten importieren
- verschiedene Variationen: index, row, column
- benchmark
- ins log speichern
- analyser -> vergleicht daten in einem document

**Comment by Pfeifenjoy** [comment]
https://www.draw.io/
