### ISSUE TITLE
Technischer Vergleich  von row bzw. column  Tabelle

### ISSUE THREAD

**Issue by jrjg** [Osslack/HANA_SSBM#7]

**Comment by Pfeifenjoy** [comment]
@jrjg kannst du noch den commit dranhängen damit jemand probe lesen kann?

**Comment by jrjg** [comment]
ja ich pushe das heute abend noch
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 22.03.17, 13:54, Arwed Mett <notifications@github.com> schrieb:
@jrjg kannst du noch den commit dranhängen damit jemand probe lesen kann?
