### ISSUE TITLE
query exec pläne

### ISSUE THREAD

**Issue by jrjg** [Osslack/HANA_SSBM#8]

**Comment by Pfeifenjoy** [comment]
@Osslack Wahrscheinlich gehst Du hier drauf ein bei den indizes?

**Comment by Pfeifenjoy** [comment]
Vielleicht kann ja noch @dominicstein etwas dazu allgemein schreiben, oder @Osslack 
packt alles in die indizes, da es da wahrscheinlich am interessantesten ist.

**Comment by Osslack** [comment]
Ich Vergleiche nur Col mit Col/Row mit Row
@dominicstein wollte Row mit Col
