### ISSUE TITLE
hana allgemein

### ISSUE THREAD

**Issue by jrjg** [Osslack/HANA_SSBM#9]

**Comment by Pfeifenjoy** [comment]
@jrjg Ich gehe davon aus dass du damit fertig bist.
Bzw. Row vs. Col ist das ja eigentlich

**Comment by jrjg** [comment]
joar zu hana allgemein hatte ich ja nix geschrieben. da brauchen wir vllt schon nochmal paar wenige zeilen zu. so von wegen hana läuft in-memory, wurde dann und dann released. aber vllt kann das alles in die einleitung, weil da sollen wir ja nicht so drauf eingehen

**Comment by Pfeifenjoy** [comment]
wie @dominicstein habe brauchen wir da nichts
